### ISSUE TITLE
Unzip error : Incorrect header check

### ISSUE THREAD

**Issue by TivoCorrmat** [romainberger/yeoman-wordpress#27]
D:\gitDEV\testWordPress>yo yo-wordpress
[?] ==========================================================================
We're constantly looking for ways to make yo better!
May we anonymously report usage statistics to improve the tool over time?
More info: yeoman.io/insight.html & http://yeoman.io
==========================================================================: Yes

Trying to get the latest stable version of Wordpress
[?] Name of the theme you want to use: (mytheme) Let's download the framework, shall we?
Downloading Wordpress version undefined

```
 info ... Fetching https://github.com/WordPress/WordPress/tarball/undefined ...
 info This might take a few moments
```

.
? Done in 0.505s.
unzip error { [Error: incorrect header check] errno: -3, code: 'Z_DATA_ERROR' }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: incorrect header check
    at Zlib._binding.onerror (zlib.js:295:17)

D:\gitDEV\testWordPress>yo yo-wordpress

Trying to get the latest stable version of Wordpress
[?] Name of the theme you want to use: (mytheme) Let's download the framework, shall we?
Downloading Wordpress version undefined

```
 info ... Fetching https://github.com/WordPress/WordPress/tarball/undefined ...
 info This might take a few moments
```

.
? Done in 0.429s.
unzip error { [Error: incorrect header check] errno: -3, code: 'Z_DATA_ERROR' }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: incorrect header check
    at Zlib._binding.onerror (zlib.js:295:17)

**Comment by romainberger** [comment]
Hi,

I just published a patch (1.2.4) that should fix it. I can't be 100% sure as I don't have a windows machine and never tested on it. Please keep me posted if it doesn't work.

**Comment by TivoCorrmat** [comment]
Hi Romain,

Still have the same error.

Taking a quick look at the code and it seems to be looking for a file "config.json" and a path ".yeoman-wordpress". I can't find any of these two in my generator-yo-wordpress folder.  Could you tell me where it is supposed to be located/generated?

Here is where the package gets all installed on Windows : 
C:\Users[UserName]\AppData\Roaming\npm\node_modules\generator-yo-wordpress

Maybe I'm just too noob and I haven't taken enough time to read about your package though. If it's the case, I'm sorry ;)

**Comment by romainberger** [comment]
The `config.json` file is supposed to be in `~/.yeoman-wordpress` on a mac, so basically in a hidden folder in the user's home folder. So it might be in `C:\Users\[UserName]\.yeoman-wordpress` in your case. 

But it doesn't seem to be what's causing the error.
Considering the line `Fetching https://github.com/WordPress/WordPress/tarball/undefined`, the git command trying to get the latest version of Wordpress returns something weird. This makes the generator fetch a wrong url so the download of the code fails.

Could you please try to run `git ls-remote --tags git://github.com/WordPress/WordPress.git | tail -n 1` in your terminal and tell me what's happening? You should get something like this: `b32b4b972eb47367fbd10c144054cdc11126288c    refs/tags/3.5.2`.

**Comment by TivoCorrmat** [comment]
Oops ... Code 18! ahahah!
Ends up installation of something isn't correctly done on my Windows or something ... tail returns an error.

I went on gitBash ... works fine!
So yeah ... I guess I'll use gitBash instead ;)

Thank you for your support and sorry for the loss of time.

**Comment by romainberger** [comment]
Ah yeah apparently the `tail` command doesn't exist on windows. 
Don't worry it's not a loss of time if something I made is not working :)

Did you find a way to make everything work?

**Comment by TivoCorrmat** [comment]
Simply had to run yo yo-wordpress on gitBash command line instead of Windows Command tool.
Works perfectly as of now :)

Thank you!

**Comment by romainberger** [comment]
Cool, sorry I couldn't help more, it's not easy without a windows machine.
Thanks for your feedback!
